name: Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: run build

      - name: Lint
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: run lint

      - name: Test
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: run test

      - name: Setup Node.js with GitHub Package Registry
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          registry-url: "https://npm.pkg.github.com"
          scope: "lookapanda"
          always-auth: true

      - name: Setup Node.js with Npm Package Registry
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          registry-url: "https://registry.npmjs.org"
          always-auth: true

      - name: Set .npmrc
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > /home/runner/work/_temp/.npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> /home/runner/work/_temp/.npmrc
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@master
        id: semantic
        with:
          branch: master
          extra_plugins: |
            @semantic-release/git
            @semantic-release/changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish To GitHub Package Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        run: npm publish --@lookapanda:registry='https://npm.pkg.github.com' --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Push updates to branch for major version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: "git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v${{steps.semantic.outputs.new_release_major_version}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
